# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20170218_1156'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='发布名称')),
                ('introduce', models.TextField(verbose_name='发布说明')),
                ('version', models.CharField(max_length=32, verbose_name='版本号')),
                ('commit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审核完成时间')),
                ('push_time', models.DateTimeField(blank=True, null=True, verbose_name='发布完成时间')),
                ('status', models.SmallIntegerField(choices=[(0, '等待审批中'), (1, '等待测试中'), (2, '已完成'), (3, '测试失败'), (4, '未知')], default=4, verbose_name='发布状态')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to=settings.AUTH_USER_MODEL, verbose_name='审批者')),
            ],
        ),
        migrations.CreateModel(
            name='CodeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(verbose_name='log')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
            },
        ),
        migrations.AlterField(
            model_name='hostgroups',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='code',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.Environment', verbose_name='发布环境'),
        ),
        migrations.AddField(
            model_name='code',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.BusinessUnit', verbose_name='项目名'),
        ),
        migrations.AddField(
            model_name='code',
            name='pusher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='code',
            name='tester',
            field=models.ManyToManyField(blank=True, null=True, related_name='t', to=settings.AUTH_USER_MODEL, verbose_name='测试者'),
        ),
    ]
