# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('token', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户token')),
                ('user_key', models.CharField(default='3TM8ucWcucyQ7FKAfe3mSds69KR3VKDK9UCXy3AJYDXvehPBtkTSPkwvFN9segcPEf4MBj8YSsrehQMXTbga9fKrXq6yDsky3gQt', max_length=100, verbose_name='用户key')),
                ('department', models.CharField(blank=True, max_length=32, null=True, verbose_name='部门')),
                ('tel', models.CharField(blank=True, max_length=32, null=True, verbose_name='座机')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
        migrations.CreateModel(
            name='CheckCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=32)),
                ('code', models.CharField(max_length=12)),
                ('times', models.IntegerField(default=1)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='权限描述')),
                ('code', models.CharField(blank=True, max_length=64, null=True, verbose_name='url权限')),
                ('method', models.CharField(blank=True, max_length=16, null=True, verbose_name='请求方法')),
                ('kwargs', models.CharField(blank=True, max_length=128, null=True, verbose_name='其他参数')),
            ],
            options={
                'verbose_name_plural': '权限',
                'verbose_name': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='角色名')),
                ('perm', models.ManyToManyField(to='accounts.Permission')),
            ],
            options={
                'verbose_name_plural': '角色',
                'verbose_name': '角色',
            },
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([('code', 'method')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(to='accounts.Role'),
        ),
    ]
