# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='d8EhXRDNus5AygxHHnUpaw3RTUcfmAnnqVR6sAd8Q6jTW5Mp3cTPJkXGTdWTAsDBPhGakPmCvW8Y5gfU8nEa5DRCt4Fvrbh8yJXT', max_length=100, verbose_name='用户key'),
        ),
    ]
