# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=64, verbose_name='url权限'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=32, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='4vN49tTEueTKDVcW8JXFxDvw6h7xcDK4yy5RH6vWqRmAxPEGXhHuHRDrcMkF6faEPYJuqBPmYTKY5RGe7KYngaUxjwvPfuRJtnY9', max_length=100, verbose_name='用户key'),
        ),
    ]
