# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='cbt6CdCUajCXWYFRTQnuas7EGRQtR3qptNSQWxJFP3s6GnAjqtmMxrEehfdWnf8qu4Yn9eDfwUGSVttJDKFvQUDTBHSmJCEEhhwE', max_length=100, verbose_name='用户key'),
        ),
    ]
