# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161228_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='j3HUXMagkVxDWDbDXEnCUTdH8GWdJ98HWujyKEEMRHDVQUc9ag96deHvKkFxJGQsDPa8eYX4a6aBjyDQHuPeavFY8Gvjxa4dvtv8', max_length=100, verbose_name='用户key'),
        ),
    ]
