# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170220_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='Vk8ndtPEWc8uQpK4jvQeRMa5fbYcUT3aSH7mND6Mp9eCnfjynrNxK6YaPQJUyFkGSsVdSEb6QBxCaDMNqGUG9uWnTaK3qKJVjbqb', max_length=100, verbose_name='用户key'),
        ),
    ]
