# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170212_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='c5ckrAdR9E8kR7d8qGcuN8P6HJMmGxPekEEj4gphU5JbVVrRBNTCmFHkv6j8vs8Q4Yys7D9SKe7utjuyfcM4wAwHt5d3uXbb48JE', max_length=100, verbose_name='用户key'),
        ),
    ]
