# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170215_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='N54xtAM5hwSu5SsHPeSWF6avFkJGtxeNMb3mmTXExhAV9MG9hwbeJJv9naA6mHAN9MNAykQx7MtW8D97NsfanpE8jjx5vTXbMRUK', max_length=100, verbose_name='用户key'),
        ),
    ]
