# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170115_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='vhuRaY7rbDVCcagSyYjrYRG6kaYrKaHMKynHJSunpnXCWau6JJ98yhwTHnHH5HP87Sq3spCcgrH6sPDmQyfXVrDgbhTNS8K4TBwT', max_length=100, verbose_name='用户key'),
        ),
    ]
