# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170115_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='nGvxdNdNTr96PSSRyKcUaKBe5vWvhgM3JkuwF9heQ8UYnTFtr3vG6QFRFJDCRG6Tpt3ASat6FuG3wNWEQG7Q3UXCjGTKShM47FVu', max_length=100, verbose_name='用户key'),
        ),
    ]
