# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170115_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='TBnq5HqFjkWbHRHV74XUDySw96wmmGFP35CDrVubMkjq4ACjeYF6sJd5hP5rqpw9nAcrtQdQsNRSDyfXD3Vxk3UqsakRq6EESPbS', max_length=100, verbose_name='用户key'),
        ),
    ]
