# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170115_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='vjabsX5etdQTq4mQgWD9WFhwEmbsFACUdtr4ht8AF9uSwURwjdsF7Hy7Qt3KPwy8qu8hdHnjQy4wGB7Wx9yPWkhheYGnTd4BHuSG', max_length=100, verbose_name='用户key'),
        ),
    ]
