# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170121_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='权限名')),
                ('codename', models.CharField(max_length=100, verbose_name='code')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='cnUvcGJpdn6t9mtSsVEwUe8cMSycNVCvJ4CfxscJh7aaCkKKArGnDEJp6vuvuY4t77A6RyCCH9RsMFDjscrScgVV4ucTFEnTtyGp', max_length=100, verbose_name='用户key'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm',
            field=models.ManyToManyField(to='accounts.Permission'),
        ),
    ]
