# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170121_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='角色名')),
                ('codename', models.CharField(max_length=100, verbose_name='code')),
            ],
            options={
                'verbose_name_plural': '角色',
                'verbose_name': '角色',
            },
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'url权限', 'verbose_name_plural': 'url权限'},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='codename',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='perm',
        ),
        migrations.AddField(
            model_name='permission',
            name='url',
            field=models.CharField(default=1, max_length=255, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='HQ6ahyMmgknVPk3quDyykT9MsHPdpTrYknxS7wTBVAyAQQ4KfFyFt4ChQxmBWK47JCb3vgdymEUxmaNS9S78hf3auxQYxxwxEKs5', max_length=100, verbose_name='用户key'),
        ),
        migrations.AddField(
            model_name='role',
            name='perm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Permission'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(to='accounts.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('perm', 'codename')]),
        ),
    ]
