# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170121_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='memo',
            field=models.CharField(default=1, max_length=255, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=32, verbose_name='角色名'),
        ),
        migrations.AddField(
            model_name='role',
            name='perm',
            field=models.ManyToManyField(to='accounts.Permission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='YUDkBCFKqwFHCnqD3yND7TEkFQFHT5UShsxfXnEgSDrwY4eqXrsc4EGVQsmbsqV5syruyhpmcExpXXW5pGK9D5Tme54tJqNjfdGj', max_length=100, verbose_name='用户key'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='role',
            name='codename',
        ),
        migrations.RemoveField(
            model_name='role',
            name='perm',
        ),
    ]
