# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170121_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='perm',
            field=models.ManyToManyField(to='accounts.Permission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='uNAmyrhQkM6Uqb5vMDkBD3C5bqQYxqhFPfpKFCfAnQcjWTRC9qNsQDj8Y7r9aRCvWjSGsyWvFpQbUP8n8jMyMEFJPdFb4QEj86vr', max_length=100, verbose_name='用户key'),
        ),
    ]
