# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170121_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='P6ShjfPDfrYfufJHQA57rdbB3AejeWFuKvp99RmymnSdJUjW7mqsbSW35UchnVGGeEB9WnVD6hQm6qd4NdUbAtdqX3nCyRFGfHqP', max_length=100, verbose_name='用户key'),
        ),
    ]
