# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170126_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='8RCF7qhC9SqtxXkW44rWCUjWECuQKH8pa9T4B6NNv9eDfXqBd64uxrVbUKaKUXK4qF4N7qqNmFDSdD36N5ktcH4wCUwjqjeJCs3m', max_length=100, verbose_name='用户key'),
        ),
    ]
