# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20170126_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='9eJPN5uPV4Knr7taqx6M6qvtWkUBDcUg6aDMYkATPShSeCSvNrhWHm4fU9JjnjfuSQnCbNY4xt6JqaUGKNDmHHEr76RTb7XrcsJB', max_length=100, verbose_name='用户key'),
        ),
    ]
