# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170126_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='TDt6HnebSYAQptDgfeFDwPMcvgBV6NStGFPF7hfUSDjYkuYGqswYrkAu6qbPdbRSpMPPJA7d4cHEyJvy9UUxubc4tRNR7uy7M649', max_length=100, verbose_name='用户key'),
        ),
    ]
