# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170126_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='wNujsdtX3n3hrNsAWsufwpusfQSXNy4wmsVDKsJuHmPHKGyXyTwmprqpGFJCmVsNxakKx95eYGuT6w6BNxEE6NvhBWJNXgvufVpU', max_length=100, verbose_name='用户key'),
        ),
    ]
