# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20170127_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='QSYu3AYnWFCu9uXfYUyYDxMvfHTkNERBc65FxxkwxvT7PPkee8XtMap569kJyB3CVgMWxkHBw4eCX9dEaERRb6A3YVnPFEvQVU5d', max_length=100, verbose_name='用户key'),
        ),
    ]
