# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20170127_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='R8BDV39NdQVnXWDh5Q7CuBEQHeghae6KDgFPDjxdmuqVdgAjnEykKWQs8pshsAfpHYwK5F7F3pD3r9CBCcCQP87QqpsSkW6xjuCq', max_length=100, verbose_name='用户key'),
        ),
    ]
