# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20170127_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='url',
        ),
        migrations.AddField(
            model_name='permission',
            name='caption',
            field=models.CharField(default=1, max_length=32, verbose_name='权限标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=64, null=True, verbose_name='url权限'),
        ),
        migrations.AddField(
            model_name='permission',
            name='f',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='kwargs',
            field=models.CharField(max_length=128, null=True, verbose_name='其他参数'),
        ),
        migrations.AddField(
            model_name='permission',
            name='method',
            field=models.CharField(max_length=16, null=True, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='permission',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='accounts.Permission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='cT4cNAy9R7YeFWBcdgufFAsCVnPc6EYKtJVcgeyvsefD4SEkX7bvFnwGMfhyQrhKHTsKQS3nFHSGRkBkDGpMasXTaAJrsNqQuyV5', max_length=100, verbose_name='用户key'),
        ),
    ]
