# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20170130_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='f',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='btTY8Kwb6JEe6URbFxXJMH5J8NWSjGpe7vvCSbBMT6W5YyY3DRaPpBG9nJBHcdRuQnxu4E3Pu8gQmudjp4BApD5cxHQAFGdhxQVt', max_length=100, verbose_name='用户key'),
        ),
    ]
