# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20170130_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleToPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '角色与权限关联',
                'verbose_name_plural': '角色与权限关联',
            },
        ),
        migrations.CreateModel(
            name='UserToRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Role')),
            ],
            options={
                'verbose_name': '用户与角色关联',
                'verbose_name_plural': '用户与角色关联',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AlterField(
            model_name='permission',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='权限描述'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='url权限'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='kwargs',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='其他参数'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='method',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='RPBFnrtBRXjVnjaJX5WR8uu38wuBbpafXnTT9axy7CfXdxUHtBFuGDEGFDhn3YE6Xx6MfxWQ88uhSXxQBgjtU9ESge8cRVMfeVEU', max_length=100, verbose_name='用户key'),
        ),
        migrations.AddField(
            model_name='usertorole',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roletopermission',
            name='perm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Permission'),
        ),
        migrations.AddField(
            model_name='roletopermission',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Role'),
        ),
    ]
