# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170130_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='perm',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='eS9p8YgqRrKj6SkVcdWVC4dE83E6DFeyCAeAESXJwPWSbpAkTxY5BXTGg3J5bdnP3FNQTDwXv3t8C5wyQ55DnymYak4m9M7qXke7', max_length=100, verbose_name='用户key'),
        ),
    ]
