# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='制造厂商'),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(verbose_name='端口'),
        ),
    ]
