# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='NetDevice',
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='nic',
            name='host',
        ),
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='插槽位'),
        ),
        migrations.AlterField(
            model_name='host',
            name='admin',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='资产管理员'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='制造厂商'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='slot',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='插槽'),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(verbose_name='端口'),
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
    ]
