# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessunit', to='assets.Host'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='assets.Host'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='assets.Host'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic', to='assets.Host'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='assets.Host'),
        ),
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='assets.Host'),
        ),
    ]
