# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20161229_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='parent_unit',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='host',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='host',
            field=models.ManyToManyField(related_name='businessunit', to='assets.Host'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='host',
        ),
        migrations.AddField(
            model_name='service',
            name='host',
            field=models.ManyToManyField(related_name='service', to='assets.Host'),
        ),
    ]
