# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20170218_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='memo',
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='sn'),
        ),
        migrations.AlterField(
            model_name='netdevice',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP'),
        ),
    ]
