# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20170212_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.ManyToManyField(null=True, to='assets.Host'),
        ),
    ]
