# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20170115_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='host',
            field=models.ManyToManyField(to='assets.Host'),
        ),
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.ManyToManyField(to='assets.Host'),
        ),
    ]
