# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20170115_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=64, verbose_name='服务名'),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='端口'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('name', 'port')]),
        ),
    ]
