# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20170115_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='host',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='service',
            field=models.ManyToManyField(to='assets.Service'),
        ),
    ]
