# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20170115_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
