# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20170121_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='admin',
            field=models.CharField(default='', max_length=32, verbose_name='资产管理员'),
        ),
    ]
