# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sql',
        ),
        migrations.RenameField(
            model_name='taskdetail',
            old_name='task',
            new_name='exec_task',
        ),
        migrations.AlterField(
            model_name='task',
            name='bind_hosts',
            field=models.ManyToManyField(blank=True, related_name='t', to='database.BindHost'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_detail',
            field=models.CharField(max_length=512, verbose_name='命令日志'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='bind_host',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='d', to='database.BindHost'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='CWdYqGJ48Nk3dcmNGtKP99U3jwrey8rvYHTX4J8vCs3tkEjw5JN8MA4cQkWTHkRev5UrYMP9GP7PdfK96rDPWF8aUvxC8RUErHc7', max_length=100, verbose_name='用户key'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdetail',
            unique_together=set([('exec_task', 'bind_host')]),
        ),
    ]
