# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170314_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_detail',
            new_name='cmd',
        ),
        migrations.RenameField(
            model_name='taskdetail',
            old_name='date',
            new_name='task_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='5k8MPMkKpmYVHHvYk3GtSxYsmWf9FR8DjdY5yPjhTUec9qS7tB7SX8A9Se3ThPcydegVQwVseWMntxvKaM67AjPMaCpruEpSdecC', max_length=100, verbose_name='用户key'),
        ),
    ]
