# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170314_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='result',
            field=models.SmallIntegerField(choices=[(0, '正在执行'), (1, '执行成功'), (2, '执行失败'), (3, '未知')], default=3, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='P4B6xUNuQrsJdbtbaU8cVmEsd65k6vb3DnaYFeSEvHP5ynrpv9AKcMreKskYpj585cd3FW67BPNKy34YybwGTVeCqEhth9wuPJYg', max_length=100, verbose_name='用户key'),
        ),
    ]
