# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20170314_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdetail',
            old_name='exec_task',
            new_name='bing_task',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='cKhGYWUyHnkGBmtMxSGEU6GUeYFF4pEeGbEmrUUtKmCuEE5DPdruhhgDJEPdckhxRdU38PR97QHPtBtNnxerMyjwaWnXe47gDNSA', max_length=100, verbose_name='用户key'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdetail',
            unique_together=set([('bing_task', 'bind_host')]),
        ),
    ]
