# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20170314_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindhost',
            name='port',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='jwXcDQgYJf8Swp8jGrkGNsjYB5gXqPTjpnbQTsue4bUYFTjWDBgb4wY5dUqgjccJxMBqrjrvXBDfdxUQBDWY7dVQTqKyAAFX5Tfa', max_length=100, verbose_name='用户key'),
        ),
    ]
