# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20170314_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='result',
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='cmd_status',
            field=models.SmallIntegerField(choices=[(0, '正在执行'), (1, '执行成功'), (2, '执行失败'), (3, '未知')], default=3, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='P9MsWRhu9m5RMthEevnA6MQEeubb6hV3c6BQmjRrAqpmUP3B9xjutYCK5AUGdAjRNXmqyS7uJcx4RvePqua94UhcxQdQN6cTjmXm', max_length=100, verbose_name='用户key'),
        ),
    ]
