# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20170315_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdetail',
            old_name='cmd_status',
            new_name='exec_status',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='JK6MAXVa7FQE5VHWDvmV3G7nPYPNgRRvnJtsQURVepKCjtGsThEdgAQDuYyFnvh3gxeNBwh9D8GBsphau8kwSxfQYeCkmPwujy6X', max_length=100, verbose_name='用户key'),
        ),
    ]
