# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20170318_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlcheck',
            old_name='sql',
            new_name='sqlsql_content',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='96GB6TcyqkcfRmuUppTxJYjW3xT7pbEDe6b6H9qcxyS9D4Cfy7Gv7NypdmDs7apE6CQwD5BJuhFMKFAR863yACAxkWY3K8aWdNTX', max_length=100, verbose_name='用户key'),
        ),
    ]
