# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20170318_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlcheck',
            name='exec_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='NdTN7sRS9mYJ4Kahu9pGW4AvdtC95PDksW9MWcRMCYsS86HfR6hJJuf7MQyTReXWsyVbewPTmMgKw6YpXqC6QKwKURCN8QkAnJW4', max_length=100, verbose_name='用户key'),
        ),
    ]
