# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20170318_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlcheck',
            name='exec_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='sqlcheck',
            name='sql_result',
            field=models.TextField(blank=True, null=True, verbose_name='sql执行结果'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='9TGHju8jn39XuUCkEpqJvXGqxgan7fQwtrGHuGj8hSAJB53D3FwvtRknAYsDcYrJBetbCwcnqF6VFrVynxkXfJpwhdutMQMAfqW8', max_length=100, verbose_name='用户key'),
        ),
    ]
