# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20170318_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('url', models.URLField(verbose_name='名称')),
                ('memo', models.CharField(max_length=256, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'url管理中心',
                'verbose_name_plural': 'url管理中心',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_key',
            field=models.CharField(default='ENAGeuGp7vyHChGEtJv3FCStkKqN36vr7fWrtdxtNmgcSgcgyfsMKMjCEa9rfap8pxbB8xbY4faqErgcGKdWaD9w4BEBcEeBx6wf', max_length=100, verbose_name='用户key'),
        ),
    ]
