# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoops', '0002_auto_20170220_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='tester',
            field=models.ManyToManyField(related_name='t', to=settings.AUTH_USER_MODEL, verbose_name='测试者'),
        ),
    ]
